mod audit;
mod changelog;
mod column_type_exemptions;
mod custom_types;
mod dependency;
mod diff;
mod drop_column_exemptions;
mod extensions;
mod extractor;
mod functions;
mod gateway_functions;
mod migration;
mod rename_column_exemptions;
mod seeder;
mod tables;
mod types;
mod verifier;

pub use audit::AuditLogger;
pub use changelog::{ChangelogManager, ChangelogEntry, ChangelogRecord, ChangeType as ChangelogChangeType};
pub use column_type_exemptions::{ColumnTypeExemption, scan_migrations_for_exemptions};
pub use custom_types::CustomTypeManager;
pub use dependency::{DependencyAnalyzer, DependencyAnalysis, TableInfo, ForeignKeyDependency};
pub use diff::{SchemaDiffChecker, SchemaDiff, SchemaChange, ChangeType, ChangeCompatibility, ColumnSchema, TableSchema, MigrationExemptions, MigrationGuards, guarded_op_token};
pub use extensions::ExtensionManager;
pub use extractor::SchemaExtractor;
pub use functions::FunctionDeployer;
pub use gateway_functions::GatewayFunctionInstaller;
pub use migration::MigrationRunner;
pub use seeder::{SeederRunner, SeederResult, SeederValidation};
pub use tables::{TableDeployer, TableDefinition, TableDeployResult};
pub use types::{TypeChecker, TypeCompatibility};
pub use verifier::{SchemaVerifier, VerificationResult};
